'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class employee
    Public Property emp_id As String
    Public Property uname As String
    Public Property password As String
    Public Property first_name As String
    Public Property last_name As String
    Public Property dob As String
    Public Property designation As String
    Public Property contact_no As String
    Public Property extra_1 As String
    Public Property extra_2 As String
    Public Property extra_3 As String

End Class
