'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class inventory
    Public Property item_id As String
    Public Property upd_date As String
    Public Property total_qty As Nullable(Of Integer)
    Public Property vendor_id As String
    Public Property out_of_stock As String
    Public Property extra_1 As String
    Public Property extra_2 As String
    Public Property extra_3 As String

End Class
