'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class item
    Public Property item_id As String
    Public Property item_name As String
    Public Property item_desc As String
    Public Property manufacturer As String
    Public Property unit_price As Nullable(Of Double)
    Public Property qty As Nullable(Of Integer)
    Public Property exp_date As String
    Public Property mfg_date As String
    Public Property prod_id As Byte()
    Public Property extra_1 As String
    Public Property extra_2 As String
    Public Property extra_3 As String

End Class
