'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class product
    Public Property prod_id As String
    Public Property prod_name As String
    Public Property prod_desc As String
    Public Property prod_price As Nullable(Of Double)

End Class
