'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class sales_details
    Public Property invoice_no As String
    Public Property prod_id As String
    Public Property unit_price As Nullable(Of Double)
    Public Property qty As Nullable(Of Integer)
    Public Property total_amount As Nullable(Of Double)
    Public Property discount As Nullable(Of Integer)
    Public Property status As String
    Public Property extra_1 As String
    Public Property extra_2 As String
    Public Property extra_3 As String
    Public Property extra_4 As String

End Class
