'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class sales_master
    Public Property invoice_no As String
    Public Property aarmount As Nullable(Of Double)
    Public Property pay_node As String
    Public Property cheque_no As String
    Public Property dd_no As String
    Public Property discount As Nullable(Of Integer)
    Public Property disc_amount As Nullable(Of Double)
    Public Property base_amount As Nullable(Of Double)
    Public Property emp_id As Byte()
    Public Property invoice_date As String
    Public Property remarks As String
    Public Property extra_1 As String
    Public Property extra_2 As String
    Public Property extra_3 As String

End Class
