'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Data.Entity
Imports System.Data.Entity.Infrastructure

Partial Public Class SalesDBEntities
    Inherits DbContext

    Public Sub New()
        MyBase.New("name=SalesDBEntities")
    End Sub

    Protected Overrides Sub OnModelCreating(modelBuilder As DbModelBuilder)
        Throw New UnintentionalCodeFirstException()
    End Sub

    Public Property employees() As DbSet(Of employee)
    Public Property inventories() As DbSet(Of inventory)
    Public Property items() As DbSet(Of item)
    Public Property products() As DbSet(Of product)
    Public Property sales_details() As DbSet(Of sales_details)
    Public Property sales_master() As DbSet(Of sales_master)
    Public Property vendors() As DbSet(Of vendor)

End Class
