'------------------------------------------------------------------------------
' <auto-generated>
'    This code was generated from a template.
'
'    Manual changes to this file may cause unexpected behavior in your application.
'    Manual changes to this file will be overwritten if the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Imports System
Imports System.Collections.Generic

Partial Public Class vendor
    Public Property vendor_id As String
    Public Property vendor_name As String
    Public Property vendor_desc As String
    Public Property vendor_addr As String
    Public Property extra_1 As String
    Public Property extra_2 As String

End Class
